CREATE TABLE [dbo].[Customer](
	[CUSTOMERID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[Surname] [nvarchar](20) NOT NULL,
	[GENDER] [char](1) NOT NULL,
	[Phone_Number] [char](11) NOT NULL,
	[Identity_Number] [char](11) NOT NULL,
	[Blood_Type] [nvarchar](6) NOT NULL,
	[Number_Of_People] [smallint] NOT NULL,
	[Room_Number] [smallint] NOT NULL,
	[Room_Type] [varchar](20) NOT NULL,
	[Date_Of_Entry] [datetime] NOT NULL,
	[Release_Date] [datetime] NOT NULL,
	[Payment] [int] NOT NULL,
	[Vehicle] [bit] NOT NULL,
	[Parking_Fee] [smallint] NULL,
	[Disability_Status] [bit] NOT NULL,
	[Additional_Services_Received] [varchar] (100) NULL,
	[Additional_Service_Price] [int] NULL,
	[Total_Price] [int] NOT NULL);